<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.8" />
    <PackageReference Include="Serilog.AspNetCore" Version="9.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\HonorBridge.Engine\HonorBridge.Engine.csproj" />
    <ProjectReference Include="..\HonorBridge.AI\HonorBridge.AI.csproj" />
    <ProjectReference Include="..\HonorBridge.Shared\HonorBridge.Shared.csproj" />
  </ItemGroup>

</Project>
