name: .NET Core Desktop

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore HonorBridge.Mac.slnf
    - name: Build
      run: dotnet build HonorBridge.Mac.slnf --no-restore
    - name: Test
      run: dotnet test HonorBridge.Mac.slnf --no-build --verbosity normal
